source/UI/Alvac.Ui.Admin/Controllers/AccountsController.cs
using Alvac.Domain.DataTransferObject;
using Alvac.Domain.Entities.Commands.AccountConnections;
using Alvac.Domain.Entities.Commands.Accounts;
using Alvac.Domain.Enum;
using Alvac.Domain.Services.Interfaces;
using Alvac.Domain.Services.Logger;
using Alvac.Ui.Admin.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace Alvac.Ui.Admin.Controllers
{
    public class AccountsController : CrudController<IEnumerable<Account>, CreateAccount, Account, UpdateAccount>
    {
        public AccountsController(IHttpClient httpClient, ILogger logger)
            : base("account", httpClient, logger)
        {
        }

        public override Task<ActionResult> Index()
        {
            return Task.FromResult<ActionResult>(View());
        }

        public async Task<ActionResult> Details(int id)
        {
            var model = await _httpClient.GetAsync<Account>(string.Format("account/{0}", id));
            return View(model);
        }

        public async Task<ActionResult> LoadTable(int draw, int start, int length)
        {
            var filter = Request.QueryString.Get("search[value]");

            string query = string.Empty;

            try
            {
                if (!string.IsNullOrEmpty(filter))
                {
                    query += "&$filter=contains(Name,'" + filter + "') or contains(Email,'" + filter + "')  or contains(LegalRepresentative,'" + filter + "') or contains(Document,'" + filter + "')";
                }

                var accounts = await _httpClient.GetAsync<ODataResponse<IEnumerable<Account>>>(string.Format("account?$inlinecount=allpages&$top={0}&$skip={1}{2}", length, start, query));
                return Json(new DataTableResponse<IEnumerable<Account>>(draw, accounts), JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return View();
            }
        }

        #region Connections
        public async Task<ActionResult> Connections(int id)
        {
            await LoadInsurersAsync();
            var model = await _httpClient.GetAsync<IEnumerable<AccountConnection>>(string.Format("account/{0}/insurers/connections", id));
            ViewBag.AccountId = id;
            return View("_Connections", model);
        }

        public async Task<ActionResult> DeleteConnection(DeleteAccountConnection command)
        {
            try
            {
                var model = await _httpClient.DeleteAsync(string.Format("account/{0}/insurers/connections/{1}", command.AccountId, command.ConnectionId));
                return Content("Conexão deletada");
            }
            catch (Exception ex)
            {
                return Content(ex.Message);
            }
        }

        public async Task<ActionResult> CreateConnection(CreateAccountConnection command)
        {
            try
            {
                var model = await _httpClient.PostAsync(string.Format("account/{0}/insurers/connections/{1}", command.AccountId, command.ConnectionId), command);
                return Content("Conexão criada");
            }
            catch (Exception ex)
            {
                return Content(ex.Message);
            }
        }

        public async Task<ActionResult> LoadConnections(RequestType requestType, int insurer)
        {
            string query = string.Empty;

            try
            {
                query += "$filter=RequestType eq Alvac.Domain.Enum.RequestType'" + (int)requestType + "' and InsurerId eq  " + (int)insurer;

                var connections = await _httpClient.GetAsync<IEnumerable<Connection>>(string.Format("connection?{0}", query));

                return Json(connections, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Content(ex.Message);
            }
        }
        #endregion

        public async Task<ActionResult> Subscriptions(int id)
        {
            ViewBag.AccountId = id;
            var model = await _httpClient.GetAsync<IEnumerable<Subscription>>(string.Format("subscription/account/{0}", id));
            return PartialView("_Subscriptions", model);
        }

        public async Task LoadInsurersAsync()
        {
            var insurers = await _httpClient.GetAsync<IEnumerable<Insurer>>("insurer");
            ViewBag.Insurers = new SelectList(insurers, "Id", "Name");
        }
    }
}

source/UI/Alvac.Ui.Admin/Controllers/ConnectionsController.cs
using Alvac.Domain.DataTransferObject;
using Alvac.Domain.Entities.Commands.Connections;
using Alvac.Domain.Services.Interfaces;
using Alvac.Domain.Services.Logger;
using Alvac.Ui.Admin.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace Alvac.Ui.Admin.Controllers
{
    public class ConnectionsController : CrudController<IEnumerable<Connection>, CreateConnection, Connection, UpdateConnection>
    {
        public ConnectionsController(IHttpClient httpClient, ILogger logger)
            : base("connection", httpClient, logger)
        {

        }

        public override async Task<ActionResult> Create()
        {
            await LoadDispatchersAsync();
            return await base.Create();
        }

        public override async Task<ActionResult> Create(CreateConnection command)
        {
            var response = await base.Create(command);

            if (!ModelState.IsValid)
            {
                await LoadDispatchersAsync();
            }

            return response;
        }

        public override async Task<ActionResult> Edit(object id)
        {
            await LoadDispatchersAsync();
            return await base.Edit(id);
        }

        public override async Task<ActionResult> Edit(UpdateConnection command)
        {
            var response = await base.Edit(command);

            if (!ModelState.IsValid)
            {
                await LoadDispatchersAsync();
            }

            return response;
        }
        
        private async Task LoadDispatchersAsync()
        {
            var dispatchers = await _httpClient.GetAsync<IEnumerable<Dispatcher>>("dispatcher");
            ViewBag.Dispatchers = new SelectList(dispatchers, "DispatcherId", "Name");
        }
    }
}

source/UI/Alvac.Ui.Admin/Controllers/InvoicesController.cs
using Alvac.Domain.DataTransferObject;
using Alvac.Domain.Services.Interfaces;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace Alvac.Ui.Admin.Controllers
{
    public class InvoicesController : Controller
    {
        private readonly IHttpClient _httpClient;

        public InvoicesController(IHttpClient client)
        {
            _httpClient = client;
        }

        public async Task<ActionResult> Index(int subscriptionId)
        {
            ViewBag.SubscriptionId = subscriptionId;
            var model = await _httpClient.GetAsync<IEnumerable<Invoice>>(string.Format("invoice/subscription/{0}?&$orderby=Closing desc", subscriptionId));
            return View(model);
        }

        public ActionResult Create(int subscriptionId)
        {
            return View();
        }
    }
}

source/UI/Alvac.Ui.Admin/Controllers/SubscriptionsController.cs
using Alvac.Domain.DataTransferObject;
using Alvac.Domain.Entities.Commands.Subscriptions;
using Alvac.Domain.Services.Interfaces;
using Alvac.Ui.Admin.Models;
using Omu.ValueInjecter;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace Alvac.Ui.Admin.Controllers
{
    public class SubscriptionsController : Controller
    {
        private readonly IHttpClient _httpClient;

        public SubscriptionsController(IHttpClient client)
        {
            _httpClient = client;
        }

        public async Task<ActionResult> Create(int accountId)
        {
            await LoadPlans();
            var model = new CreateSubscription
            {
                AccountId = accountId
            };

            return View(model);
        }

        [HttpPost]
        public async Task<ActionResult> Create(CreateSubscription command)
        {
            var response = await _httpClient.PostAsync(string.Format("subscription/account/{0}", command.AccountId), command);
            if (response.IsSuccessStatusCode)
            {
                TempData["toastr"] = new ToastrMessage(TraceLevel.Verbose, "Criado com sucesso");
                return RedirectToAction("Details", "Accounts", new { id = command.AccountId });
            }

            await LoadPlans();
            ModelState.AddModelError(string.Empty, await response.Content.ReadAsStringAsync());
            return View(command);
        }

        public async Task<ActionResult> Edit(int id)
        {
            await LoadPlans();

            var model = await _httpClient.GetAsync<Subscription>(string.Format("subscription/{0}", id));
            var command = Mapper.Map<UpdateSubscription>(model);
            return View(command);
        }

        [HttpPost]
        public async Task<ActionResult> Edit(UpdateSubscription command)
        {
            var response = await _httpClient.PutAsync(string.Format("subscription/{0}", command.SubscriptionId), command);
            if (response.IsSuccessStatusCode)
            {
                TempData["toastr"] = new ToastrMessage(TraceLevel.Verbose, "Criado com sucesso");
                return RedirectToAction("Details", "Accounts", new { id = command.AccountId });
            }

            await LoadPlans();
            ModelState.AddModelError(string.Empty, await response.Content.ReadAsStringAsync());
            return View(command);
        }

        private async Task LoadPlans()
        {
            var plans = await _httpClient.GetAsync<IEnumerable<Plan>>(string.Format("plan"));
            ViewBag.Plans = new SelectList(plans, "PlanId", "Name");
        }
    }
}

source/UI/Alvac.Ui.Admin/Views/Accounts/Create.cshtml
@model Alvac.Domain.Entities.Commands.Accounts.CreateAccount

@{
    ViewBag.Title = "Create";
    ViewBag.BreadTitle = "Criação de cliente";
    ViewBag.BreadDescription = "Crie um novo cliente no sistema";
}

<div class="row">
    <div class="col-md-12">
        <section class="panel">
            @using (Html.BeginForm())
            {
                <div class="form-horizontal">
                    <hr />
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="form-group">
                        @Html.LabelFor(model => model.LegalRepresentative, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.LegalRepresentative, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.LegalRepresentative, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Susep, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Susep, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Susep, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Document, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Document, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Document, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.ZipCode, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.ZipCode, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.ZipCode, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Street, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Street, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Street, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Neighborhood, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Neighborhood, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Neighborhood, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.State, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.State, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.State, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.ChargeEmail, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.ChargeEmail, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.ChargeEmail, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.MobilePhone, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.MobilePhone, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.MobilePhone, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Site, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Site, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Site, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            @Html.ActionLink("Cancelar", "Index", null, new { @class = "btn btn-danger" })

                            <input type="submit" value="Salvar" class="btn btn-success" />
                        </div>
                    </div>
                </div>
            }
        </section>
    </div>
</div>

source/UI/Alvac.Ui.Admin/Views/Accounts/Delete.cshtml
@model Alvac.Domain.DataTransferObject.Account

@{
    ViewBag.Title = "Delete";
    ViewBag.BreadTitle = "Cliente";
    ViewBag.BreadDescription = "Deletar um cliente no sistema";
}

<div class="row">
    <div class="col-md-12">
        <h3>Tem certeza que deseja deletar?</h3>
        <div>
            <hr />
            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.LegalRepresentative)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.LegalRepresentative)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Susep)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Susep)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Document)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Document)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Name)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Name)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.ZipCode)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.ZipCode)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Street)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Street)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Neighborhood)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Neighborhood)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.State)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.State)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.City)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.City)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Email)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Email)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.ChargeEmail)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.ChargeEmail)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Phone)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Phone)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.MobilePhone)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.MobilePhone)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Site)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Site)
                </dd>

            </dl>


            @using (Html.BeginForm("PostDelete", "Accounts"))
            {
                @Html.Hidden("id", Model.AccountId)

                <div class="form-actions no-color">
                    @Html.ActionLink("Cancelar", "Index", null, new { @class = "btn btn-danger" })

                    <input type="submit" value="Excluir" class="btn btn-success" />
                </div>
            }
        </div>
    </div>
</div>

source/UI/Alvac.Ui.Admin/Views/Accounts/Details.cshtml
@model Alvac.Domain.DataTransferObject.Account

<div class="row">
    <div class="col-md-12">
        <div class="box-tab">
            <ul class="nav nav-tabs">
                <li class="active">
                    <a href="#cliente" data-toggle="tab">Dados do cliente</a>
                </li>
                <li class="">
                    <a href="#assinatura" onclick="loadSubscriptions(@Model.AccountId)" data-toggle="tab">Assinaturas</a>
                </li>
                <li class="">
                    <a href="#conexao" onclick="loadConnections(@Model.AccountId)" data-toggle="tab">Conexões</a>
                </li>
            </ul>
            <div class="tab-content">
                <div class="tab-pane fade active in" id="cliente">
                    <div class="col-md-12">
                        <dl class="dl-horizontal">
                            <dt>
                                @Html.DisplayNameFor(model => model.LegalRepresentative)
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.LegalRepresentative)
                            </dd>

                            <dt>
                                @Html.DisplayNameFor(model => model.Susep)
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.Susep)
                            </dd>

                            <dt>
                                @Html.DisplayNameFor(model => model.Document)
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.Document)
                            </dd>

                            <dt>
                                @Html.DisplayNameFor(model => model.Name)
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.Name)
                            </dd>

                            <dt>
                                @Html.DisplayNameFor(model => model.ZipCode)
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.ZipCode)
                            </dd>

                            <dt>
                                @Html.DisplayNameFor(model => model.Street)
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.Street)
                            </dd>

                            <dt>
                                @Html.DisplayNameFor(model => model.Neighborhood)
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.Neighborhood)
                            </dd>

                            <dt>
                                @Html.DisplayNameFor(model => model.State)
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.State)
                            </dd>

                            <dt>
                                @Html.DisplayNameFor(model => model.City)
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.City)
                            </dd>

                            <dt>
                                @Html.DisplayNameFor(model => model.Email)
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.Email)
                            </dd>

                            <dt>
                                @Html.DisplayNameFor(model => model.ChargeEmail)
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.ChargeEmail)
                            </dd>

                            <dt>
                                @Html.DisplayNameFor(model => model.Phone)
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.Phone)
                            </dd>

                            <dt>
                                @Html.DisplayNameFor(model => model.MobilePhone)
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.MobilePhone)
                            </dd>

                            <dt>
                                @Html.DisplayNameFor(model => model.Site)
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.Site)
                            </dd>

                        </dl>
                    </div>
                </div>

                <div class="tab-pane fade" id="assinatura">
                </div>

                <div class="tab-pane fade" id="conexao">
                </div>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">

    function loadSubscriptions(accountId) {
        var url = "/Accounts/Subscriptions/" + accountId;
        $.get(url, function (data) {
            $("#assinatura").html(data);
        });
    }

    function loadConnections(accountId) {
        var url = "/Accounts/Connections/" + accountId;
        $.get(url, function (data) {
            $("#conexao").html(data);
        });
    }
</script>

source/UI/Alvac.Ui.Admin/Views/Accounts/_Subscriptions.cshtml
@model IEnumerable<Alvac.Domain.DataTransferObject.Subscription>

@{
    Layout = null;
}

<div class="row mt25 mb25">
    <div class="col-xs-12">
        <a href="@Url.Action("Create", "Subscriptions", new { accountId = ViewBag.AccountId })" class="btn btn-primary pull-right">
            <i class="ti-share mr5"></i>Adicionar nova assinatura
        </a>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <section class="panel panel-default">
            <div class="panel-body">
                <div class="table-responsive">
                    <table class="table table-striped table-bordered responsive no-m datatable">
                        <thead>
                            <tr>
                                <th>
                                    @Html.DisplayNameFor(model => model.PlanName)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.RequestType)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.Type)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.Status)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.Created)
                                </th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.PlanName)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.RequestType)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Type)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Status)
                                    </td>
                                    <td>
                                        @item.Created.ToLocalTime().ToString("dd/MM/yyyy HH:mm:ss")
                                    </td>
                                    <td>
                                        <a href="@Url.Action("Edit", "Subscriptions", new { id = item.SubscriptionId })" title="Editar">
                                            <span class="ti-pencil-alt"></span>
                                        </a>
                                        <a href="@Url.Action("Index", "Invoices", new { subscriptionId = item.SubscriptionId })" title="Faturas">
                                            <span class="ti-align-center"></span>
                                        </a>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </section>
    </div>
</div>