source/UI/Alvac.Ui.Admin/Controllers/PlansController.cs
using Alvac.Domain.DataTransferObject;
using Alvac.Domain.Entities.Commands.Plans;
using Alvac.Domain.Services.Interfaces;
using Alvac.Domain.Services.Logger;
using Alvac.Ui.Admin.Models;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Configuration;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace Alvac.Ui.Admin.Controllers
{
    public class PlansController : CrudController<IEnumerable<Plan>, CreatePlan, Plan, UpdatePlan>
    {
        #region Private Fields

        private readonly ILogger _logger;

        #endregion

        public PlansController(ILogger logger, IHttpClient httpClient)
            : base("plan", httpClient, logger)
        {
            _logger = logger;
        }
    }
}

source/UI/Alvac.Ui.Admin/Views/Plans/Create.cshtml
@model Alvac.Domain.Entities.Commands.Plans.CreatePlan

@{
    ViewBag.Title = "Criação de Plano";
    ViewBag.BreadTitle = "Criação de plano";
    ViewBag.BreadDescription = "Crie um novo plano no sistema";
}
<div class="row">
    <div class="col-md-12">

        @using (Html.BeginForm())
        {
            <div class="form-horizontal">
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                <div class="form-group">
                    @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Amount, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Amount, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Amount, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.RecurrenceType, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EnumFor(model => model.RecurrenceType, "Selecione", new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.RecurrenceType, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Recurrence, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Recurrence, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Recurrence, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Trial, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Trial, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Trial, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Value, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Value, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Value, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.AdditionalValue, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.AdditionalValue, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.AdditionalValue, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.IsActive, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.IsActive)
                        @Html.ValidationMessageFor(model => model.IsActive, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        @Html.ActionLink("Cancelar", "Index", null, new { @class = "btn btn-danger" })

                        <input type="submit" value="Salvar" class="btn btn-success" />
                    </div>
                </div>
            </div>
        }
    </div>
</div>

source/UI/Alvac.Ui.Admin/Views/Plans/Delete.cshtml
@model Alvac.Domain.DataTransferObject.Plan

@{
    ViewBag.Title = "Delete";
}


<div class="row">
    <div class="col-md-12">
        <h3>Tem certeza que deseja deletar?</h3>
        <div>
            <hr />
            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.Name)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Name)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Recurrence)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Recurrence)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Amount)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Amount)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Value)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Value)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.AdditionalValue)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.AdditionalValue)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Trial)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Trial)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.IsActive)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.IsActive)
                </dd>
            </dl>

            @using (Html.BeginForm("PostDelete", "Plans"))
            {
                @Html.Hidden("id", Model.PlanId)

                <div class="form-actions no-color">
                    @Html.ActionLink("Cancelar", "Index", null, new { @class = "btn btn-danger" })

                    <input type="submit" value="Excluir" class="btn btn-success" />
                </div>
            }
        </div>
    </div>
</div>

source/UI/Alvac.Ui.Admin/Views/Plans/Edit.cshtml
@model Alvac.Domain.Entities.Commands.Plans.UpdatePlan

@{
    ViewBag.Title = "Edit";
    ViewBag.BreadTitle = "Edição de plano";
    ViewBag.BreadDescription = "Edite um plano no sistema";
}

<div class="row">
    <div class="col-md-12">
        @using (Html.BeginForm())
        {
            @Html.HiddenFor(x => x.PlanId)

            <div class="form-horizontal">
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                <div class="form-group">
                    @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.RecurrenceType, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EnumFor(model => model.RecurrenceType, "Selecione", new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.RecurrenceType, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Recurrence, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Recurrence, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Recurrence, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Amount, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Amount, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Amount, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Value, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Value, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Value, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.AdditionalValue, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.AdditionalValue, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.AdditionalValue, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Trial, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Trial, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Trial, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.IsActive, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        <div class="checkbox">
                            @Html.EditorFor(model => model.IsActive)
                            @Html.ValidationMessageFor(model => model.IsActive, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        @Html.ActionLink("Cancelar", "Index", null, new { @class = "btn btn-danger" })

                        <input type="submit" value="Salvar" class="btn btn-success" />
                    </div>
                </div>
            </div>
        }
    </div>
</div>

source/UI/Alvac.Ui.Admin/Views/Plans/Index.cshtml
@model IEnumerable<Plan>

@{
    ViewBag.Title = "Index";
    ViewBag.BreadTitle = "Planos";
    ViewBag.BreadDescription = "Listagem de planos do sistema";
}

<div class="row mt25 mb25">
    <div class="col-xs-12">
        <a href="Plans/Create" class="btn btn-primary pull-right">
            <i class="ti-share mr5"></i>Criar novo plano
        </a>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <section class="panel panel-default">
            <div class="panel-body">
                <div class="table-responsive">
                    <table class="table table-striped table-bordered mg-t datatable" data-sortable="" data-sortable-initialized="true">
                        <thead>
                            <tr>
                                <th>@Html.DisplayNameFor(model => model.Name)</th>
                                <th>@Html.DisplayNameFor(model => model.RecurrenceType)</th>
                                <th>@Html.DisplayNameFor(model => model.Recurrence)</th>
                                <th>@Html.DisplayNameFor(model => model.Amount)</th>
                                <th>@Html.DisplayNameFor(model => model.Value)</th>
                                <th>@Html.DisplayNameFor(model => model.IsActive)</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @if (Model != null)
                            {
                                foreach (var item in Model)
                                {
                                    <tr>
                                        <td>@Html.DisplayFor(modelItem => item.Name)</td>
                                        <td>@Html.DisplayFor(modelItem => item.RecurrenceType)</td>
                                        <td>@Html.DisplayFor(modelItem => item.Recurrence)</td>
                                        <td>@Html.DisplayFor(modelItem => item.Amount)</td>
                                        <td>@Html.DisplayFor(modelItem => item.Value)</td>
                                        <td>@Html.DisplayFor(modelItem => item.IsActive)</td>
                                        <td>
                                            <a href="@Url.Action("Edit", new { id = item.PlanId })"><span class="ti-pencil-alt"></span></a>
                                            <a href="@Url.Action("Delete", new { id = item.PlanId })"><span class="ti-trash"></span></a>
                                        </td>
                                    </tr>
                                }
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </section>
    </div>
</div>

@section scripts{
    <script type="text/javascript">
        $('.datatable').dataTable({
            language: {
                url: "/plugins/datatables/pt-br.js"
            },
        });
    </script>
}