source/UI/Alvac.Ui.Admin/Controllers/DispatchersController.cs
using Alvac.Domain.DataTransferObject;
using Alvac.Domain.Entities.Commands.Dispatchers;
using Alvac.Domain.Services.Interfaces;
using Alvac.Domain.Services.Logger;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Threading.Tasks;

namespace Alvac.Ui.Admin.Controllers
{
    public class DispatchersController : CrudController<IEnumerable<Dispatcher>, CreateDispatcher, Dispatcher, UpdateDispatcher>
    {
        public DispatchersController(IHttpClient httpClient, ILogger logger)
            : base("dispatcher", httpClient, logger)
        {
        }

        public override async Task<ActionResult> Create()
        {
            await LoadInsurersAsync();
            return await base.Create();
        }

        public override async Task<ActionResult> Create(CreateDispatcher command)
        {
            await LoadInsurersAsync();
            return await base.Create(command);
        }

        public override async Task<ActionResult> Edit(object id)
        {
            await LoadInsurersAsync();
            return await base.Edit(id);
        }

        public override async Task<ActionResult> Edit(UpdateDispatcher command)
        {
            await LoadInsurersAsync();
            return await base.Edit(command);
        }

        public async Task LoadInsurersAsync()
        {
            var insurers = await _httpClient.GetAsync<IEnumerable<Insurer>>("insurer");
            ViewBag.Insurers = new SelectList(insurers, "Id", "Name");
        }
    }
}

source/UI/Alvac.Ui.Admin/Views/Dispatchers/Create.cshtml
@model Alvac.Domain.Entities.Commands.Dispatchers.CreateDispatcher


@{
    ViewBag.Title = "Create";
    ViewBag.BreadTitle = "Criação de despachante";
    ViewBag.BreadDescription = "Crie um novo despachante no sistema";
}

<div class="row">
    <div class="col-md-12">

        @using (Html.BeginForm())
        {
            <div class="form-horizontal">
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.InsurerId, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownListFor(model => model.InsurerId, (SelectList)ViewBag.Insurers, "Selecione", new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.InsurerId, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Technology, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EnumFor(model => model.Technology, "Selecione", new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Technology, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.RequestType, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EnumFor(model => model.RequestType, "Selecione", new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.RequestType, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.IsActive, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.IsActive)
                        @Html.ValidationMessageFor(model => model.IsActive, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        @Html.ActionLink("Cancelar", "Index", null, new { @class = "btn btn-danger" })

                        <input type="submit" value="Salvar" class="btn btn-success" />
                    </div>
                </div>
            </div>
        }
    </div>
</div>

source/UI/Alvac.Ui.Admin/Views/Dispatchers/Delete.cshtml
@model Alvac.Domain.DataTransferObject.Dispatcher

@{
    ViewBag.Title = "Delete";
    ViewBag.BreadTitle = "Despachante";
    ViewBag.BreadDescription = "Deletar um despachante no sistema";
}

<div class="row">
    <div class="col-md-12">
        <h3>Tem certeza que deseja deletar?</h3>
        <div>
            <hr />
            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.Name)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Name)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Description)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Description)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Insurer)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Insurer)
                </dd>


                <dt>
                    @Html.DisplayNameFor(model => model.Technology)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Technology)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.RequestType)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.RequestType)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.IsActive)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.IsActive)
                </dd>

            </dl>

            @using (Html.BeginForm("PostDelete", "Dispatchers"))
            {
                @Html.Hidden("id", Model.DispatcherId)

                <div class="form-actions no-color">
                    @Html.ActionLink("Cancelar", "Index", null, new { @class = "btn btn-danger" })

                    <input type="submit" value="Excluir" class="btn btn-success" />
                </div>
            }
        </div>
    </div>
</div>

source/UI/Alvac.Ui.Admin/Views/Dispatchers/Edit.cshtml
@model Alvac.Domain.Entities.Commands.Dispatchers.UpdateDispatcher


@{
    ViewBag.Title = "Create";
    ViewBag.BreadTitle = "Editar despachante";
    ViewBag.BreadDescription = "Edite um despachante no sistema";
}

<div class="row">
    <div class="col-md-12">
        @using (Html.BeginForm())
        {
            <div class="form-horizontal">
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                @Html.HiddenFor(model => model.DispatcherId)

                <div class="form-group">
                    @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.InsurerId, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownListFor(model => model.InsurerId, (SelectList)ViewBag.Insurers, "Selecione", new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.InsurerId, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Technology, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EnumFor(model => model.Technology, "Selecione", new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Technology, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.RequestType, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EnumFor(model => model.RequestType, "Selecione", new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.RequestType, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.IsActive, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.IsActive)
                        @Html.ValidationMessageFor(model => model.IsActive, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        @Html.ActionLink("Cancelar", "Index", null, new { @class = "btn btn-danger" })

                        <input type="submit" value="Salvar" class="btn btn-success" />
                    </div>
                </div>
            </div>
        }
    </div>
</div>

source/UI/Alvac.Ui.Admin/Views/Dispatchers/Index.cshtml
@model IEnumerable<Alvac.Domain.DataTransferObject.Dispatcher>

@{
    ViewBag.Title = "Index";
    ViewBag.BreadTitle = "Despachantes";
    ViewBag.BreadDescription = "Listagem de despachantes do sistema";
}

<div class="row mt25 mb25">
    <div class="col-xs-12">
        <a href="@Url.Action("Create")" class="btn btn-primary pull-right">
            <i class="ti-share mr5"></i>Criar novo dispacther
        </a>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <section class="panel panel-default">
            <div class="panel-body">
                <div class="table-responsive">
                    <table class="table table-striped table-bordered responsive no-m datatable" data-sortable="" data-sortable-initialized="true">
                        <thead>
                            <tr>
                                <th>
                                    @Html.DisplayNameFor(model => model.Name)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.Description)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.IsActive)
                                </th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Name)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Description)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.IsActive)
                                    </td>
                                    <td>
                                        <a href="@Url.Action("Edit", new { id = item.DispatcherId })"><span class="ti-pencil-alt"></span></a>
                                        <a href="@Url.Action("Delete", new { id = item.DispatcherId })"><span class="ti-trash"></span></a>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>


            </div>
        </section>
    </div>
</div>

@section scripts{
    <script type="text/javascript">
        $('.datatable').dataTable({
            language: {
                url: "/plugins/datatables/pt-br.js"
            },
        });
    </script>
}