source/UI/Alvac.Ui.Admin/Controllers/ConnectionsController.cs
using Alvac.Domain.DataTransferObject;
using Alvac.Domain.Entities.Commands.Connections;
using Alvac.Domain.Services.Interfaces;
using Alvac.Domain.Services.Logger;
using Alvac.Ui.Admin.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace Alvac.Ui.Admin.Controllers
{
    public class ConnectionsController : CrudController<IEnumerable<Connection>, CreateConnection, Connection, UpdateConnection>
    {
        public ConnectionsController(IHttpClient httpClient, ILogger logger)
            : base("connection", httpClient, logger)
        {

        }

        public override async Task<ActionResult> Create()
        {
            await LoadDispatchersAsync();
            return await base.Create();
        }

        public override async Task<ActionResult> Create(CreateConnection command)
        {
            var response = await base.Create(command);

            if (!ModelState.IsValid)
            {
                await LoadDispatchersAsync();
            }

            return response;
        }

        public override async Task<ActionResult> Edit(object id)
        {
            await LoadDispatchersAsync();
            return await base.Edit(id);
        }

        public override async Task<ActionResult> Edit(UpdateConnection command)
        {
            var response = await base.Edit(command);

            if (!ModelState.IsValid)
            {
                await LoadDispatchersAsync();
            }

            return response;
        }
        
        private async Task LoadDispatchersAsync()
        {
            var dispatchers = await _httpClient.GetAsync<IEnumerable<Dispatcher>>("dispatcher");
            ViewBag.Dispatchers = new SelectList(dispatchers, "DispatcherId", "Name");
        }
    }
}

source/UI/Alvac.Ui.Admin/Views/Connections/Create.cshtml
@model Alvac.Domain.Entities.Commands.Connections.CreateConnection

@{
    ViewBag.Title = "Create";
    ViewBag.BreadTitle = "Criação de conexão";
    ViewBag.BreadDescription = "Crie uma nova conexão no sistema";
}

<div class="row">
    <div class="col-md-12">
        <section class="panel">
            @using (Html.BeginForm())
            {
                <div class="form-horizontal">
                    <hr />
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                    <div class="form-group">
                        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.DispatcherId, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.DropDownListFor(model => model.DispatcherId, (SelectList)ViewBag.Dispatchers, "Selecione", new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.DispatcherId, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.MaxThroughput, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.MaxThroughput, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.MaxThroughput, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.LengthTimeUnitThroughput, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.LengthTimeUnitThroughput, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.LengthTimeUnitThroughput, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.WindowSize, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.WindowSize, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.WindowSize, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Amount, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Amount, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Amount, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.InputQueueName, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.InputQueueName, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.InputQueueName, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.OutputQueueName, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.OutputQueueName, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.OutputQueueName, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.NotificationQueueName, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.NotificationQueueName, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.NotificationQueueName, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.RetryMax, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.RetryMax, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.RetryMax, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.RetryInterval, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.RetryInterval, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.RetryInterval, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.IsActive, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            <div class="checkbox">
                                @Html.EditorFor(model => model.IsActive)
                                @Html.ValidationMessageFor(model => model.IsActive, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.IsDefault, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            <div class="checkbox">
                                @Html.EditorFor(model => model.IsDefault)
                                @Html.ValidationMessageFor(model => model.IsDefault, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            @Html.ActionLink("Cancelar", "Index", null, new { @class = "btn btn-danger" })

                            <input type="submit" value="Salvar" class="btn btn-success" />
                        </div>
                    </div>
                </div>
            }
        </section>
    </div>
</div>

source/UI/Alvac.Ui.Admin/Views/Connections/Delete.cshtml
@model Alvac.Domain.DataTransferObject.Connection

@{
    ViewBag.Title = "Delete";
    ViewBag.BreadTitle = "Plano";
    ViewBag.BreadDescription = "Deletar um plano no sistema";
}

<div class="row">
    <div class="col-md-12">
        <h3>Tem certeza que deseja deletar?</h3>
        <div>
            <hr />
            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.DispatcherId)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.DispatcherId)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Name)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Name)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.MaxThroughput)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.MaxThroughput)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.LengthTimeUnitThroughput)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.LengthTimeUnitThroughput)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.WindowSize)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.WindowSize)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Amount)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Amount)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.InputQueueName)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.InputQueueName)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.OutputQueueName)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.OutputQueueName)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.NotificationQueueName)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.NotificationQueueName)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.IsActive)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.IsActive)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.IsDefault)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.IsDefault)
                </dd>

            </dl>

            @using (Html.BeginForm("PostDelete", "Connections"))
            {
                @Html.Hidden("id", Model.ConnectionId)

                <div class="form-actions no-color">
                    @Html.ActionLink("Cancelar", "Index", null, new { @class = "btn btn-danger" })

                    <input type="submit" value="Excluir" class="btn btn-success" />
                </div>
            }
        </div>
    </div>
</div>

source/UI/Alvac.Ui.Admin/Views/Connections/Edit.cshtml
@model Alvac.Domain.Entities.Commands.Connections.UpdateConnection

@{
    ViewBag.Title = "Edit";
    ViewBag.BreadTitle = "Edicão de conexão";
    ViewBag.BreadDescription = "Editando uma conexão no sistema";
}

<div class="row">
    <div class="col-md-12">
        @using (Html.BeginForm())
        {
            <div class="form-horizontal">
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                @Html.HiddenFor(model => model.ConnectionId)

                <div class="form-group">
                    @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.DispatcherId, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownListFor(model => model.DispatcherId, (SelectList)ViewBag.Dispatchers, "Selecione", new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.DispatcherId, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.MaxThroughput, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.MaxThroughput, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.MaxThroughput, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.LengthTimeUnitThroughput, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.LengthTimeUnitThroughput, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.LengthTimeUnitThroughput, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.WindowSize, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.WindowSize, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.WindowSize, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Amount, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Amount, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Amount, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.InputQueueName, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.InputQueueName, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.InputQueueName, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.OutputQueueName, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.OutputQueueName, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.OutputQueueName, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.NotificationQueueName, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.NotificationQueueName, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.NotificationQueueName, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.RetryMax, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.RetryMax, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.RetryMax, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.RetryInterval, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.RetryInterval, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.RetryInterval, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.IsActive, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        <div class="checkbox">
                            @Html.EditorFor(model => model.IsActive)
                            @Html.ValidationMessageFor(model => model.IsActive, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.IsDefault, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        <div class="checkbox">
                            @Html.EditorFor(model => model.IsDefault)
                            @Html.ValidationMessageFor(model => model.IsDefault, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        @Html.ActionLink("Cancelar", "Index", null, new { @class = "btn btn-danger" })

                        <input type="submit" value="Salvar" class="btn btn-success" />
                    </div>
                </div>
            </div>
        }

    </div>
</div>

source/UI/Alvac.Ui.Admin/Views/Connections/Index.cshtml
@model IEnumerable<Connection>

@{
    ViewBag.Title = "Index";
    ViewBag.BreadTitle = "Conexões";
    ViewBag.BreadDescription = "Listagem de conexões do sistema";
}

<div class="row mt25 mb25">
    <div class="col-xs-12">
        <a href="@Url.Action("Create")" class="btn btn-primary pull-right">
            <i class="ti-share mr5"></i>Criar nova conexão
        </a>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <section class="panel panel-default">
            <div class="panel-body">
                <div class="table-responsive">
                    <table class="table table-striped table-bordered responsive no-m datatable" data-sortable="" data-sortable-initialized="true">
                        <thead>
                            <tr>
                                <th>
                                    @Html.DisplayNameFor(model => model.Name)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.WindowSize)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.MaxThroughput)
                                </th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Name)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.WindowSize)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.MaxThroughput)
                                    </td>
                                    <td>
                                        <a href="@Url.Action("Edit", new { id = item.ConnectionId })"><span class="ti-pencil-alt"></span></a>
                                        <a href="@Url.Action("Delete", new { id = item.ConnectionId })"><span class="ti-trash"></span></a>
                                        <a href="@Url.Action("Index", "ConnectionParameters", new { connectionId = item.ConnectionId})"><span class="ti-view-list" title="Parâmetros da Conexão"></span></a>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </section>
    </div>
</div>

@section scripts
{
    <script type="text/javascript">
        $('.datatable').dataTable({
            language: {
                url: "/plugins/datatables/pt-br.js"
            },
        });
    </script>
}